name: User Service Test

on:
  workflow_dispatch:
  
  push:
    branches: [ "**" ]

  pull_request:
    branches: [ "main" ]


defaults:
 run:
  working-directory: ./

jobs:
  test:

    runs-on: ubuntu-latest
    environment: 
      name: Test

    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ secrets.JWT_SECRET_KEY }}
      - run: printenv