name: User Service Test

on:
  workflow_dispatch:
  
  push:
    branches: [ "**" ]

  pull_request:
    branches: [ "main" ]


defaults:
 run:
  working-directory: ./

jobs:
  test:

    runs-on: ubuntu-latest
    environment: 
      name: Test
      url: https://github.com

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      
        with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
        
      - run: echo ${{ secrets.JWT_SECRET_KEY }}